In [26]:
import numpy as np
import matplotlib.pyplot as plt

In [27]:
import sys

def load_data():

    lInf = []

    f=open('data/inferno.txt', encoding="ISO-8859-1")

    for line in f:
        lInf.append(line.strip())
    f.close()

    lPur = []

    f=open('data/purgatorio.txt', encoding="ISO-8859-1")

    for line in f:
        lPur.append(line.strip())
    f.close()

    lPar = []

    f=open('data/paradiso.txt', encoding="ISO-8859-1")

    for line in f:
        lPar.append(line.strip())
    f.close()
    
    return lInf, lPur, lPar

def split_data(l, n):

    lTrain, lTest = [], []
    for i in range(len(l)):
        if i % n == 0:
            lTest.append(l[i])
        else:
            lTrain.append(l[i])
            
    return lTrain, lTest

if __name__ == '__main__':

    # Load the tercets and split the lists in training and test lists
    
    lInf, lPur, lPar = load_data()

    lInf_train, lInf_evaluation = split_data(lInf, 4)
    lPur_train, lPur_evaluation = split_data(lPur, 4)
    lPar_train, lPar_evaluation = split_data(lPar, 4)
    
    print(lInf_train)

['Ahi quanto a dir qual era è cosa dura esta selva selvaggia e aspra e forte che nel pensier rinova la paura', 'Tant è amara che poco è più morte ma per trattar del ben chi vi trovai dirò de laltre cose chi vho scorte', 'Io non so ben ridir com i vintrai tant era pien di sonno a quel punto che la verace via abbandonai', 'guardai in alto e vidi le sue spalle vestite giÃ\xa0 de raggi del pianeta che mena dritto altrui per ogne calle', 'Allor fu la paura un poco queta che nel lago del cor mera durata la notte chi passai con tanta pieta', 'E come quei che con lena affannata uscito fuor del pelago a la riva si volge a lacqua perigliosa e guata', 'Poi chèi posato un poco il corpo lasso ripresi via per la piaggia diserta sì che l piè fermo sempre era l più basso', 'Ed ecco quasi al cominciar de lerta una lonza leggera e presta molto che di pel macolato era coverta', 'e non mi si partia dinanzi al volto anzi mpediva tanto il mio cammino chi fui per ritornar più volte vòlto', 'mosse 

In [28]:
lInf_train

['Ahi quanto a dir qual era è cosa dura esta selva selvaggia e aspra e forte che nel pensier rinova la paura',
 'Tant è amara che poco è più morte ma per trattar del ben chi vi trovai dirò de laltre cose chi vho scorte',
 'Io non so ben ridir com i vintrai tant era pien di sonno a quel punto che la verace via abbandonai',
 'guardai in alto e vidi le sue spalle vestite giÃ\xa0 de raggi del pianeta che mena dritto altrui per ogne calle',
 'Allor fu la paura un poco queta che nel lago del cor mera durata la notte chi passai con tanta pieta',
 'E come quei che con lena affannata uscito fuor del pelago a la riva si volge a lacqua perigliosa e guata',
 'Poi chèi posato un poco il corpo lasso ripresi via per la piaggia diserta sì che l piè fermo sempre era l più basso',
 'Ed ecco quasi al cominciar de lerta una lonza leggera e presta molto che di pel macolato era coverta',
 'e non mi si partia dinanzi al volto anzi mpediva tanto il mio cammino chi fui per ritornar più volte vòlto',

In [29]:
#Creazione dizionario con tutte le parole

def initDict(allTercets):
    allwords= {}
    eps= 0.001
    for t in allTercets:
        words = [w.lower() for w in t.split()]
        for w in words:
            if w not in allwords:
                allwords[w]=eps
    
    return allwords

allwords=initDict(lInf_train+lPur_train+lPar_train)
allwords

{'ahi': 0.001,
 'quanto': 0.001,
 'a': 0.001,
 'dir': 0.001,
 'qual': 0.001,
 'era': 0.001,
 'ã¨': 0.001,
 'cosa': 0.001,
 'dura': 0.001,
 'esta': 0.001,
 'selva': 0.001,
 'selvaggia': 0.001,
 'e': 0.001,
 'aspra': 0.001,
 'forte': 0.001,
 'che': 0.001,
 'nel': 0.001,
 'pensier': 0.001,
 'rinova': 0.001,
 'la': 0.001,
 'paura': 0.001,
 'tant': 0.001,
 'amara': 0.001,
 'poco': 0.001,
 'piã¹': 0.001,
 'morte': 0.001,
 'ma': 0.001,
 'per': 0.001,
 'trattar': 0.001,
 'del': 0.001,
 'ben': 0.001,
 'chi': 0.001,
 'vi': 0.001,
 'trovai': 0.001,
 'dirã²': 0.001,
 'de': 0.001,
 'laltre': 0.001,
 'cose': 0.001,
 'vho': 0.001,
 'scorte': 0.001,
 'io': 0.001,
 'non': 0.001,
 'so': 0.001,
 'ridir': 0.001,
 'com': 0.001,
 'i': 0.001,
 'vintrai': 0.001,
 'pien': 0.001,
 'di': 0.001,
 'sonno': 0.001,
 'quel': 0.001,
 'punto': 0.001,
 'verace': 0.001,
 'via': 0.001,
 'abbandonai': 0.001,
 'guardai': 0.001,
 'in': 0.001,
 'alto': 0.001,
 'vidi': 0.001,
 'le': 0.001,
 'sue': 0.001,
 'spalle': 0.001,
 've

In [30]:
infernowords=allwords.copy()
purgatoriowords=allwords.copy()
paradisowords=allwords.copy()

In [ ]:

#Per ogni cantica calcoliamo logPIc,j=log(Ncj/Nc) che andremo poi ad usare per il ML
def getLogPiPerCanticasWord(cantica,wordsOfCantica):
    
    eps=0.001
    for c in cantica:
        words=c.split()
        for w in words:
            if w in wordsOfCantica.keys():
                val=wordsOfCantica.get(w)
                val=val+1
                wordsOfCantica[w]=val
            else:
                wordsOfCantica[w]=eps
    n_words=len(wordsOfCantica.keys())
    
    for w, v in list(wordsOfCantica.items()):
        wordsOfCantica[w] = np.log(v / n_words)
        
    

getLogPiPerCanticasWord(lInf_train,infernowords)
getLogPiPerCanticasWord(lPar_train,paradisowords)
getLogPiPerCanticasWord(lPur_train,purgatoriowords)

infernowords
paradisowords
purgatoriowords


{'ahi': np.float64(-16.329652333020608),
 'quanto': np.float64(-5.784284578868867),
 'a': np.float64(-3.279857497915794),
 'dir': np.float64(-6.330809147167729),
 'qual': np.float64(-5.49005181366324),
 'era': np.float64(-5.378828242498165),
 'ã¨': np.float64(-16.329652333020608),
 'cosa': np.float64(-6.4774054446780776),
 'dura': np.float64(-8.322951487580243),
 'esta': np.float64(-9.42089755370539),
 'selva': np.float64(-8.322951487580243),
 'selvaggia': np.float64(-8.728249998436876),
 'e': np.float64(-2.6117535013881112),
 'aspra': np.float64(-9.42089755370539),
 'forte': np.float64(-6.936907074389168),
 'che': np.float64(-2.6095508597515877),
 'nel': np.float64(-5.530056347972824),
 'pensier': np.float64(-8.728249998436876),
 'rinova': np.float64(-9.42089755370539),
 'la': np.float64(-3.1642275504488566),
 'paura': np.float64(-7.812259161601705),
 'tant': np.float64(-8.728249998436876),
 'amara': np.float64(-9.42089755370539),
 'poco': np.float64(-5.7083005973877),
 'piã¹': np.flo

In [39]:
def getlloftercets(allvalues,dictCantica):
    
   
    llf=np.zeros(len(allvalues))
    index=0
    
    for row in allvalues:
        words=row.split()
        ll=0
        
        for w in words:
            if w.lower() in dictCantica:
                ll+=dictCantica[w.lower()]
        llf[index]=ll
        index+=1
   
    return llf

llfInferno=getlloftercets(lInf_evaluation+lPar_evaluation+lPur_evaluation,infernowords)
llfParadiso=getlloftercets(lInf_evaluation+lPar_evaluation+lPur_evaluation,paradisowords)
llfPurgatorio=getlloftercets(lInf_evaluation+lPar_evaluation+lPur_evaluation,purgatoriowords)

llfParadiso,llfInferno,llfPurgatorio



(array([-123.63663901, -154.69406241, -152.65208259, ..., -164.9875631 ,
        -132.75334669, -145.13336414], shape=(1204,)),
 array([-119.15976844, -140.32220626, -151.60650698, ..., -186.05358398,
        -120.61579835, -146.82524652], shape=(1204,)),
 array([-111.60985315, -159.47042005, -142.64367991, ..., -182.83349223,
        -133.00111508, -138.92380822], shape=(1204,)))

In [40]:
def initSjoint(llf1,llf2,llf3):
    logS = np.vstack([llf1, llf2, llf3])  # shape (3, N)

    # Passaggio in likelihood (non strettamente necessario per classificazione, ma richiesto dall'esercizio)
    S = np.exp(logS)  # shape (3, N)

    # Calcolo delle densità con priori (uniformi)
    P_c = 1.0 / 3
    SJoint = S * P_c  # shape (3, N)
    return SJoint
Sjoint=initSjoint(llfInferno,llfParadiso,llfPurgatorio)
Sjoint

array([[5.92173332e-53, 3.81697117e-62, 4.79743771e-67, ...,
        5.25816106e-82, 1.38071198e-53, 5.72116375e-65],
       [6.73238063e-55, 2.18827075e-68, 1.68624868e-67, ...,
        7.40782146e-73, 7.39320631e-59, 3.10641561e-64],
       [1.12547382e-49, 1.84397610e-70, 3.74555071e-63, ...,
        1.31613962e-80, 5.77069844e-59, 1.54538051e-61]], shape=(3, 1204))

In [41]:
def vrow(M):
    M.reshape(1,-1)
    return M
SMarginal = vrow(Sjoint.sum(0))
SMarginal

array([1.12607273e-49, 3.81697338e-62, 3.74619908e-63, ...,
       7.40782159e-73, 1.38072514e-53, 1.54905904e-61], shape=(1204,))

In [42]:
SPOST=Sjoint/SMarginal
SPOST

array([[5.25874855e-04, 9.99999422e-01, 1.28061472e-04, ...,
        7.09812054e-10, 9.99990466e-01, 3.69331548e-04],
       [5.97863750e-06, 5.73299978e-07, 4.50122550e-05, ...,
        9.99999982e-01, 5.35458224e-06, 2.00535649e-03],
       [9.99468147e-01, 4.83099021e-09, 9.99826926e-01, ...,
        1.77668914e-08, 4.17946938e-06, 9.97625312e-01]], shape=(3, 1204))

In [43]:
predicted_labels= np.argmax(SPOST,axis=0)
predicted_labels

array([2, 0, 2, ..., 1, 0, 2], shape=(1204,))

In [44]:
labels={
    0:"inferno",
    1:"purgatorio",
    2:"paradiso"
}
cnt=0
for l in predicted_labels:
    print(f'predicted label for tercet {cnt} is: {labels[l]}')
    cnt+=1

predicted label for tercet 0 is: paradiso
predicted label for tercet 1 is: inferno
predicted label for tercet 2 is: paradiso
predicted label for tercet 3 is: paradiso
predicted label for tercet 4 is: paradiso
predicted label for tercet 5 is: purgatorio
predicted label for tercet 6 is: paradiso
predicted label for tercet 7 is: purgatorio
predicted label for tercet 8 is: paradiso
predicted label for tercet 9 is: paradiso
predicted label for tercet 10 is: paradiso
predicted label for tercet 11 is: purgatorio
predicted label for tercet 12 is: paradiso
predicted label for tercet 13 is: purgatorio
predicted label for tercet 14 is: purgatorio
predicted label for tercet 15 is: inferno
predicted label for tercet 16 is: purgatorio
predicted label for tercet 17 is: inferno
predicted label for tercet 18 is: paradiso
predicted label for tercet 19 is: inferno
predicted label for tercet 20 is: inferno
predicted label for tercet 21 is: purgatorio
predicted label for tercet 22 is: paradiso
predicted la