In [1]:
import numpy as np

In [2]:
a1= np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
a2= np.array([[1,2,3],[3,4,5]])
a2

array([[1, 2, 3],
       [3, 4, 5]])

In [4]:
a2.size #quanti sono gli elementi

6

In [5]:
a1.shape #forma, tupla nxm

(3,)

In [6]:
a2.shape

(2, 3)

In [7]:
a2.ndim #numero di dimensioni

2

In [8]:
z= np.zeros((3,2)) #soli zero, posso mettere anche un solo numero per avere un array

In [9]:
z

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
o= np.ones(3) #stessa cosa ma di soli uno
o

array([1., 1., 1.])

In [11]:
line= np.linspace(0,5, 10) #array di 10 numeri equidistanti 
line

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [12]:
I=np.eye(3) #Matrice identità
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
v1 = np.array([10, 20, 30])                # vettore unidimensionale
v2 = np.array([[1, 2], [3, 4]])            # vettore bidimensionale (matrice 2x2)
v3 = np.array([[[5, 6], [7, 8]], [[9, 10], [11, 12]]])  # vettore tridimensionale (2x2x2)

print("Unidimensionale:", v1)
print("Bidimensionale:\n", v2)
print("Tridimensionale:\n", v3)

Unidimensionale: [10 20 30]
Bidimensionale:
 [[1 2]
 [3 4]]
Tridimensionale:
 [[[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [14]:
#Accesso mediante indice al primo vettore a 20
v1[1]

np.int64(20)

In [15]:
#Accesso mediante indice al secondo vettore a 3
v2[1,0]

np.int64(3)

In [16]:
#Accesso mediante indice al terzo vettore a 10
v3[1,0,1]

np.int64(10)

In [17]:
#Intervalli di indici al terzo vettore per ottenere 5,7,9,11
v3[:,:,0]

array([[ 5,  7],
       [ 9, 11]])

In [18]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

mul=arr1.dot(arr2.T) #(Ho trasposto arr2 per renderlo compatibile con la moltiplicazione di matrici)
mul

array([[ 50,  68],
       [122, 167]])

In [19]:
#reshape serve a cambiare la forma dell'array
arr3=arr1.reshape((6,))
arr3

array([1, 2, 3, 4, 5, 6])

In [20]:
#l'alternativa per avere un array monodimensionale è
arr4=arr1.ravel()
arr4

array([1, 2, 3, 4, 5, 6])

In [21]:
# Creo un array bidimensionale (matrice 3x3) con valori a piacere
array2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2d


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
array2d.sum(axis=0) #somma delle righe

array([12, 15, 18])

In [23]:
array2d.sum(axis=1) #somma delle colonne

array([ 6, 15, 24])

In [24]:
array2d.min(axis=0) #minimo delle righe

array([1, 2, 3])

In [25]:
xmask=array2d % 2==0
#andiamo a prendere i numeri pari di array2d
array2d[xmask]

array([2, 4, 6, 8])

In [29]:
array_3x1 = np.ones((3, ))*4
array_3x1 

array([4., 4., 4.])

In [30]:
array2d+array_3x1

array([[ 5.,  6.,  7.],
       [ 8.,  9., 10.],
       [11., 12., 13.]])

In [31]:
array_3x2 = np.random.rand(3, 2)
array_1x2 = np.random.rand(1, 2)

print("Array (3,2):\n", array_3x2)
print("Array (1,2):\n", array_1x2)

Array (3,2):
 [[0.90465241 0.8773643 ]
 [0.004295   0.97021835]
 [0.98277027 0.93769873]]
Array (1,2):
 [[0.8684921  0.40229388]]


In [32]:
array_3x2+array_1x2

array([[1.77314451, 1.27965818],
       [0.8727871 , 1.37251223],
       [1.85126237, 1.33999261]])