In [1]:
import numpy as np

In [2]:
a1= np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
a2= np.array([[1,2,3],[3,4,5]])
a2

array([[1, 2, 3],
       [3, 4, 5]])

In [4]:
a2.size #quanti sono gli elementi

6

In [5]:
a1.shape #forma, tupla nxm

(3,)

In [6]:
a2.shape

(2, 3)

In [7]:
a2.ndim #numero di dimensioni

2

In [8]:
z= np.zeros((3,2)) #soli zero, posso mettere anche un solo numero per avere un array

In [9]:
z

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
o= np.ones(3) #stessa cosa ma di soli uno
o

array([1., 1., 1.])

In [11]:
line= np.linspace(0,5, 10) #array di 10 numeri equidistanti 
line

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [ ]:
I=np.eye()