In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import sklearn.datasets
def load_iris():
    D,L = sklearn.datasets.load_iris()['data'].T, sklearn.datasets.load_iris()['target']
    return D, L
D,L=load_iris()

In [3]:
D

array([[5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
        4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
        5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
        5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
        6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
        6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
        6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
        6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
        6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
        7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
        7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
        6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9],
       [3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3. ,
        3. , 4. , 4.4, 3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3. ,
       

In [4]:
L

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
def split_db_2to1(D, L, seed=0):
    nTrain = int(D.shape[1]*2.0/3.0)
    np.random.seed(seed)
    idx = np.random.permutation(D.shape[1])
    idxTrain = idx[0:nTrain]
    idxTest = idx[nTrain:]
    DTR = D[:, idxTrain]
    DTE = D[:, idxTest]
    LTR = L[idxTrain]
    LTE = L[idxTest]
    return (DTR, LTR), (DTE, LTE)
    D, L = load_iris()
    # DTR and LTR are training data and labels, DTE and LTE are evaluation (or more precisely validation) data and labels
(DTR, LTR), (DTE, LTE) = split_db_2to1(D, L)

In [22]:
D0=DTR[:,LTR==0]
D0 #Sono i dati con la label 0

array([[5.5, 5. , 5. , 4.9, 4.8, 5.4, 4.8, 4.4, 4.6, 5.1, 5. , 5.2, 5.7,
        4.7, 5. , 5.4, 4.8, 5.3, 4.3, 5.4, 5.7, 4.6, 4.6, 4.8, 5.1, 4.8,
        4.5, 4.9, 4.4, 5. , 5.1],
       [4.2, 3.4, 3.5, 3.6, 3. , 3.9, 3.4, 2.9, 3.6, 3.8, 3.4, 3.5, 3.8,
        3.2, 3.5, 3.7, 3.1, 3.7, 3. , 3.4, 4.4, 3.1, 3.4, 3. , 3.8, 3.4,
        2.3, 3. , 3.2, 3.6, 3.5],
       [1.4, 1.5, 1.3, 1.4, 1.4, 1.3, 1.9, 1.4, 1. , 1.9, 1.6, 1.5, 1.7,
        1.3, 1.6, 1.5, 1.6, 1.5, 1.1, 1.7, 1.5, 1.5, 1.4, 1.4, 1.6, 1.6,
        1.3, 1.4, 1.3, 1.4, 1.4],
       [0.2, 0.2, 0.3, 0.1, 0.3, 0.4, 0.2, 0.2, 0.2, 0.4, 0.4, 0.2, 0.3,
        0.2, 0.6, 0.2, 0.2, 0.2, 0.1, 0.2, 0.4, 0.2, 0.3, 0.1, 0.2, 0.2,
        0.3, 0.2, 0.2, 0.2, 0.3]])

In [19]:
D0.mean(1).shape

(4,)

In [11]:
D1=DTR[:,LTR==1]
D2=DTR[:,LTR==2]

In [ ]:
def getMuAndCov(D):
    mu=D.mean(1) #in questo modo abbiamo la media delle caratteristiche
    mu=mu.reshape((mu.size, 1))
    DC=np.dot((D-mu),(D-mu).T)
    C=DC/D.shape[1]
    return mu,C
mu0,C0=getMuAndCov(D0) #vengono utilizzati i dati di training per calcolare le medie e le matrici di covarianza
mu1,C1=getMuAndCov(D1)
mu2,C2=getMuAndCov(D2)

In [23]:
mu0,C0

(array([[4.96129032],
        [3.42903226],
        [1.46451613],
        [0.2483871 ]]),
 array([[0.13140479, 0.11370447, 0.02862643, 0.01187305],
        [0.11370447, 0.16270552, 0.01844953, 0.01117586],
        [0.02862643, 0.01844953, 0.03583767, 0.00526535],
        [0.01187305, 0.01117586, 0.00526535, 0.0108845 ]]))

In [24]:
mu1,C1

(array([[5.91212121],
        [2.78484848],
        [4.27272727],
        [1.33939394]]),
 array([[0.26470156, 0.09169881, 0.18366391, 0.05134068],
        [0.09169881, 0.10613407, 0.08898072, 0.04211203],
        [0.18366391, 0.08898072, 0.21955923, 0.06289256],
        [0.05134068, 0.04211203, 0.06289256, 0.03208448]]))

In [25]:
mu2,C2

(array([[6.45555556],
        [2.92777778],
        [5.41944444],
        [1.98888889]]),
 array([[0.30080247, 0.08262346, 0.18614198, 0.04311728],
        [0.08262346, 0.08533951, 0.06279321, 0.05114198],
        [0.18614198, 0.06279321, 0.18434414, 0.04188272],
        [0.04311728, 0.05114198, 0.04188272, 0.0804321 ]]))

In [ ]:
def logpdf_GAU_ND(X, mu, C):
    """
    Compute the log-density of a multivariate Gaussian distribution for multiple samples.

    Parameters:
    X : numpy.ndarray of shape (M, N)
        The data matrix (M features, N samples).
    mu : numpy.ndarray of shape (M, 1)
        The mean vector.
    C : numpy.ndarray of shape (M, M)
        The covariance matrix.

    Returns:
    numpy.ndarray
        The array of log-density values (N,).
    """
    M = X.shape[0]
    XC = X - mu
    invC = np.linalg.inv(C)
    log_det_C = np.linalg.slogdet(C)[1]
    term1 = -0.5 * M * np.log(2 * np.pi)
    term2 = -0.5 * log_det_C
    term3 = -0.5 * np.sum(XC * (invC @ XC), axis=0)
    return term1 + term2 + term3

ll0=logpdf_GAU_ND(DTE,mu0,C0) #Utilizzo i dati da validare
ll1=logpdf_GAU_ND(DTE,mu1,C1)
ll2=logpdf_GAU_ND(DTE,mu2,C2)

ll0,ll1,ll2

(array([ 1.55967572e+00,  1.14017174e+00, -1.40657517e+02, -4.17161807e+02,
        -4.79793093e+02,  2.41007437e+00,  2.10494245e+00,  1.67400801e+00,
        -1.70961371e+02, -1.66665979e+02,  7.06271117e-01, -9.73464551e-01,
        -1.51986858e+02, -2.45521190e-01, -5.63754861e+02, -7.67214078e+01,
        -4.20761218e+02, -1.65272890e+02, -7.85138635e-01, -2.42586918e+02,
        -4.06216307e+00, -4.88360403e+02,  2.17363495e+00,  1.81394319e+00,
        -3.95752259e+02,  2.37180771e+00, -4.04665187e+02, -1.38807386e+02,
        -1.18431556e+02, -8.29839492e+01, -3.56324460e+02, -3.48262925e+02,
        -2.27427204e+02, -2.46143837e+02,  8.75894828e-01, -9.77609722e+01,
        -4.03297575e+02, -2.91264978e+02,  2.38446728e+00, -1.76880387e+02,
        -1.37384611e+02, -2.41764742e+02, -1.73726267e+02, -1.47937484e+00,
         1.59429843e+00,  1.15000214e+00, -3.23352247e+02, -1.20234441e+02,
        -4.86995891e+02,  2.22922516e+00]),
 array([-5.23573716e+01, -7.42164838e+01, -1

In [33]:
def initSjoint(ll0,ll1,ll2):
    logS = np.vstack([ll0, ll1, ll2])  # shape (3, N)

    # Passaggio in likelihood (non strettamente necessario per classificazione, ma richiesto dall'esercizio)
    S = np.exp(logS)  # shape (3, N)

    # Calcolo delle densità con priori (uniformi)
    P_c = 1.0 / 3
    SJoint = S * P_c  # shape (3, N)
    return SJoint
Sjoint=initSjoint(ll0,ll1,ll2)
Sjoint

array([[1.58575943e+000, 1.04243514e+000, 2.72957564e-062,
        2.24806026e-182, 1.41705326e-209, 3.71159641e+000,
        2.73554357e+000, 1.77783391e+000, 1.88494475e-075,
        1.38281331e-073, 6.75473622e-001, 1.25923986e-001,
        3.27963237e-067, 2.60765569e-001, 4.86691243e-246,
        1.59659471e-034, 6.14615463e-184, 5.56896774e-073,
        1.52018824e-001, 1.47475180e-106, 5.73724955e-003,
        2.69557088e-213, 2.93005929e+000, 2.04486323e+000,
        4.46535964e-173, 3.57224919e+000, 6.01202795e-177,
        1.73618815e-061, 1.22661255e-052, 3.04373991e-037,
        5.93105804e-156, 1.88023605e-152, 5.65586443e-100,
        4.20695998e-108, 8.00340945e-001, 1.16366505e-043,
        2.36030153e-176, 1.06685624e-127, 3.61775980e+000,
        5.06643905e-078, 7.20278540e-061, 3.35571731e-106,
        1.18718880e-076, 7.59266808e-002, 1.64162425e+000,
        1.05273322e+000, 1.23817483e-141, 2.02173642e-053,
        1.05499498e-212, 3.09755432e+000],
       [6.086

In [36]:
def vrow(x):
	return x.reshape((1, x.size))
#Calcoliamo ora le probabilità a posteriori
def getSPost(Sjoint):
    SMarginal=vrow(Sjoint.sum(0))
    Spost=Sjoint/SMarginal
    return Spost
Spost=getSPost(Sjoint)
Spost

array([[1.00000000e+000, 1.00000000e+000, 9.35681540e-062,
        5.75063125e-182, 1.38742252e-207, 1.00000000e+000,
        1.00000000e+000, 1.00000000e+000, 3.66921886e-075,
        3.28548075e-073, 1.00000000e+000, 1.00000000e+000,
        4.73773100e-067, 1.00000000e+000, 3.23377386e-240,
        1.03988553e-033, 1.22693978e-180, 2.68588568e-072,
        1.00000000e+000, 1.07779007e-105, 1.00000000e+000,
        2.84496941e-210, 1.00000000e+000, 1.00000000e+000,
        7.46172719e-172, 1.00000000e+000, 6.68149661e-176,
        9.78087515e-062, 1.04699282e-052, 3.12772907e-036,
        1.58138477e-155, 1.51421514e-151, 3.81388355e-099,
        3.07091067e-107, 1.00000000e+000, 3.61141619e-043,
        7.05320574e-176, 2.21700238e-127, 1.00000000e+000,
        1.26605476e-077, 1.09315585e-060, 9.89183305e-105,
        1.32276686e-075, 1.00000000e+000, 1.00000000e+000,
        1.00000000e+000, 3.27286598e-141, 6.32513224e-052,
        1.49557593e-209, 1.00000000e+000],
       [3.838

In [37]:
predicted_labels= np.argmax(Spost,axis=0)
predicted_labels

array([0, 0, 1, 2, 2, 0, 0, 0, 1, 1, 0, 0, 1, 0, 2, 1, 2, 1, 0, 2, 0, 2,
       0, 0, 2, 0, 2, 1, 1, 1, 2, 2, 2, 1, 0, 1, 2, 2, 0, 1, 1, 2, 1, 0,
       0, 0, 2, 1, 2, 0])

In [38]:
accuracy = (predicted_labels == LTE).mean()
print("Accuracy:", accuracy)    

Accuracy: 0.96
